name: Build Frosting

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - frontend/**
      - .github/workflows/frontend.yaml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/javabin/frosting:${{ github.sha }}
            ghcr.io/javabin/frosting:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Create staging
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/javabin/frosting:staging \
            ghcr.io/javabin/frosting:latest

      - name: Generate summary
        run: |
          echo "Tag: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        working-directory: frontend
