name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create release tag from staging cupcake
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/javabin/cupcake:release \
            ghcr.io/javabin/cupcake:staging

      - name: Create version tag from staging cupcake
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/javabin/cupcake:${{ github.ref_name }} \
            ghcr.io/javabin/cupcake:staging

      - name: Create release tag from staging frosting
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/javabin/frosting:release \
            ghcr.io/javabin/cupcake:staging

      - name: Create version tag from staging frosting
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/javabin/frosting:${{ github.ref_name }} \
            ghcr.io/javabin/cupcake:staging
